# Generated by Django 5.0.14 on 2025-12-25 17:11

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('call_published', 'Call Published'), ('application_received', 'Application Received'), ('feasibility_request', 'Feasibility Review Request'), ('feasibility_reminder', 'Feasibility Review Reminder'), ('feasibility_rejected', 'Feasibility Rejected'), ('evaluation_assigned', 'Evaluation Assigned'), ('evaluation_reminder', 'Evaluation Reminder'), ('resolution_accepted', 'Resolution: Accepted'), ('resolution_pending', 'Resolution: Pending (Waiting List)'), ('resolution_rejected', 'Resolution: Rejected'), ('acceptance_reminder', 'Acceptance Reminder'), ('access_scheduled', 'Access Scheduled'), ('publication_followup', 'Publication Follow-up')], help_text='Type of email template', max_length=50, unique=True)),
                ('subject', models.CharField(help_text='Email subject line (supports template variables)', max_length=200)),
                ('html_content', models.TextField(help_text='HTML email body (supports Django template syntax)')),
                ('text_content', models.TextField(help_text='Plain text email body (supports Django template syntax)')),
                ('available_variables', models.TextField(blank=True, help_text='JSON or text describing available template variables')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'ordering': ['template_type'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmailTemplate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('call_published', 'Call Published'), ('application_received', 'Application Received'), ('feasibility_request', 'Feasibility Review Request'), ('feasibility_reminder', 'Feasibility Review Reminder'), ('feasibility_rejected', 'Feasibility Rejected'), ('evaluation_assigned', 'Evaluation Assigned'), ('evaluation_reminder', 'Evaluation Reminder'), ('resolution_accepted', 'Resolution: Accepted'), ('resolution_pending', 'Resolution: Pending (Waiting List)'), ('resolution_rejected', 'Resolution: Rejected'), ('acceptance_reminder', 'Acceptance Reminder'), ('access_scheduled', 'Access Scheduled'), ('publication_followup', 'Publication Follow-up')], db_index=True, help_text='Type of email template', max_length=50)),
                ('subject', models.CharField(help_text='Email subject line (supports template variables)', max_length=200)),
                ('html_content', models.TextField(help_text='HTML email body (supports Django template syntax)')),
                ('text_content', models.TextField(help_text='Plain text email body (supports Django template syntax)')),
                ('available_variables', models.TextField(blank=True, help_text='JSON or text describing available template variables')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Email Template',
                'verbose_name_plural': 'historical Email Templates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_call_published', models.BooleanField(default=True, help_text='Receive notifications when new calls are published')),
                ('notify_application_updates', models.BooleanField(default=True, help_text='Receive updates about your applications')),
                ('notify_evaluation_assigned', models.BooleanField(default=True, help_text='Receive notifications when evaluations are assigned to you')),
                ('notify_feasibility_requests', models.BooleanField(default=True, help_text='Receive feasibility review requests (for node coordinators)')),
                ('notify_reminders', models.BooleanField(default=True, help_text='Receive reminder emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(help_text='Email address sent to', max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('html_content', models.TextField(blank=True)),
                ('text_content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_call_id', models.IntegerField(blank=True, null=True)),
                ('related_application_id', models.IntegerField(blank=True, null=True)),
                ('related_evaluation_id', models.IntegerField(blank=True, null=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_received', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='communications.emailtemplate')),
            ],
            options={
                'verbose_name': 'Email Log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='communicati_created_b43a91_idx'), models.Index(fields=['status'], name='communicati_status_e10043_idx'), models.Index(fields=['recipient_email'], name='communicati_recipie_da9135_idx')],
            },
        ),
    ]
