# Generated by Django 5.0.14 on 2026-02-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('call_published', 'Call Published'), ('application_received', 'Application Received'), ('feasibility_request', 'Feasibility Review Request'), ('feasibility_reminder', 'Feasibility Review Reminder'), ('feasibility_rejected', 'Feasibility Rejected'), ('evaluation_assigned', 'Evaluation Assigned'), ('evaluation_reminder', 'Evaluation Reminder'), ('evaluation_overdue', 'Evaluation Overdue (to Evaluator)'), ('coordinator_overdue_evaluations', 'Overdue Evaluations (to Coordinator)'), ('coordinator_evaluations_locked', 'Evaluations Locked Out (to Coordinator)'), ('evaluations_complete', 'All Evaluations Complete'), ('resolution_accepted', 'Resolution: Accepted'), ('resolution_pending', 'Resolution: Pending (Waiting List)'), ('resolution_rejected', 'Resolution: Rejected'), ('acceptance_reminder', 'Acceptance Reminder'), ('access_scheduled', 'Access Scheduled'), ('publication_followup', 'Publication Follow-up')], help_text='Type of email template', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalemailtemplate',
            name='template_type',
            field=models.CharField(choices=[('call_published', 'Call Published'), ('application_received', 'Application Received'), ('feasibility_request', 'Feasibility Review Request'), ('feasibility_reminder', 'Feasibility Review Reminder'), ('feasibility_rejected', 'Feasibility Rejected'), ('evaluation_assigned', 'Evaluation Assigned'), ('evaluation_reminder', 'Evaluation Reminder'), ('evaluation_overdue', 'Evaluation Overdue (to Evaluator)'), ('coordinator_overdue_evaluations', 'Overdue Evaluations (to Coordinator)'), ('coordinator_evaluations_locked', 'Evaluations Locked Out (to Coordinator)'), ('evaluations_complete', 'All Evaluations Complete'), ('resolution_accepted', 'Resolution: Accepted'), ('resolution_pending', 'Resolution: Pending (Waiting List)'), ('resolution_rejected', 'Resolution: Rejected'), ('acceptance_reminder', 'Acceptance Reminder'), ('access_scheduled', 'Access Scheduled'), ('publication_followup', 'Publication Follow-up')], db_index=True, help_text='Type of email template', max_length=50),
        ),
    ]
