# Generated by Django 5.0.14 on 2026-08-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_alter_emailtemplate_template_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('call_announced', 'Call Announced (Opens Soon)'), ('call_published', 'Call Published'), ('equipment_consult_request', 'Equipment Consult Request (to Node Coordinator)'), ('equipment_consult_confirmation', 'Equipment Consult Confirmation (to Requester)'), ('application_received', 'Application Received'), ('feasibility_request', 'Feasibility Review Request'), ('feasibility_consult_request', 'Feasibility Consult Request'), ('feasibility_reminder', 'Feasibility Review Reminder'), ('feasibility_complete', 'Feasibility Review Complete'), ('feasibility_rejected', 'Feasibility Rejected'), ('feasibility_edits_requested', 'Feasibility: Edits Requested'), ('evaluation_assigned', 'Evaluation Assigned'), ('evaluation_reminder', 'Evaluation Reminder'), ('evaluation_overdue', 'Evaluation Overdue (to Evaluator)'), ('coordinator_overdue_evaluations', 'Overdue Evaluations (to Coordinator)'), ('coordinator_evaluations_locked', 'Evaluations Locked Out (to Coordinator)'), ('evaluations_complete', 'All Evaluations Complete'), ('resolution_accepted', 'Resolution: Accepted'), ('resolution_pending', 'Resolution: Pending (Waiting List)'), ('resolution_rejected', 'Resolution: Rejected'), ('handoff_notification', 'Handoff Notification'), ('acceptance_reminder', 'Acceptance Reminder'), ('acceptance_expired', 'Acceptance Expired'), ('access_scheduled', 'Access Scheduled'), ('publication_followup', 'Publication Follow-up'), ('waitlist_digest', 'Waitlist Digest (to Node Coordinator)'), ('waitlist_not_reached', 'Waitlist: Not Reached This Call'), ('freed_capacity_notice', 'Freed Capacity Notice (to Node Coordinator)'), ('completion_reminder', 'Completion Reminder (to Applicant)'), ('completion_reminder_coordinator', 'Completion Reminder (to Node Coordinator)')], help_text='Type of email template', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalemailtemplate',
            name='template_type',
            field=models.CharField(choices=[('call_announced', 'Call Announced (Opens Soon)'), ('call_published', 'Call Published'), ('equipment_consult_request', 'Equipment Consult Request (to Node Coordinator)'), ('equipment_consult_confirmation', 'Equipment Consult Confirmation (to Requester)'), ('application_received', 'Application Received'), ('feasibility_request', 'Feasibility Review Request'), ('feasibility_consult_request', 'Feasibility Consult Request'), ('feasibility_reminder', 'Feasibility Review Reminder'), ('feasibility_complete', 'Feasibility Review Complete'), ('feasibility_rejected', 'Feasibility Rejected'), ('feasibility_edits_requested', 'Feasibility: Edits Requested'), ('evaluation_assigned', 'Evaluation Assigned'), ('evaluation_reminder', 'Evaluation Reminder'), ('evaluation_overdue', 'Evaluation Overdue (to Evaluator)'), ('coordinator_overdue_evaluations', 'Overdue Evaluations (to Coordinator)'), ('coordinator_evaluations_locked', 'Evaluations Locked Out (to Coordinator)'), ('evaluations_complete', 'All Evaluations Complete'), ('resolution_accepted', 'Resolution: Accepted'), ('resolution_pending', 'Resolution: Pending (Waiting List)'), ('resolution_rejected', 'Resolution: Rejected'), ('handoff_notification', 'Handoff Notification'), ('acceptance_reminder', 'Acceptance Reminder'), ('acceptance_expired', 'Acceptance Expired'), ('access_scheduled', 'Access Scheduled'), ('publication_followup', 'Publication Follow-up'), ('waitlist_digest', 'Waitlist Digest (to Node Coordinator)'), ('waitlist_not_reached', 'Waitlist: Not Reached This Call'), ('freed_capacity_notice', 'Freed Capacity Notice (to Node Coordinator)'), ('completion_reminder', 'Completion Reminder (to Applicant)'), ('completion_reminder_coordinator', 'Completion Reminder (to Node Coordinator)')], db_index=True, help_text='Type of email template', max_length=50),
        ),
    ]
