# Generated by Django 5.0.6 on 2026-01-01 11:49

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEvaluation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('score_relevance', models.IntegerField(blank=True, help_text='Scientific relevance and originality (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('score_methodology', models.IntegerField(blank=True, help_text='Methodology and experimental design (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('score_contributions', models.IntegerField(blank=True, help_text='Expected contributions and results (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('score_impact', models.IntegerField(blank=True, help_text='Impact and strengths (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('score_opportunity', models.IntegerField(blank=True, help_text='Opportunity criteria (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, help_text='Computed total score', max_digits=4, null=True)),
                ('comments', models.TextField(blank=True, help_text='Evaluator comments')),
                ('assigned_at', models.DateTimeField(blank=True, editable=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('application', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='applications.application')),
                ('evaluator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical evaluation',
                'verbose_name_plural': 'historical evaluations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_relevance', models.IntegerField(blank=True, help_text='Scientific relevance and originality (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('score_methodology', models.IntegerField(blank=True, help_text='Methodology and experimental design (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('score_contributions', models.IntegerField(blank=True, help_text='Expected contributions and results (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('score_impact', models.IntegerField(blank=True, help_text='Impact and strengths (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('score_opportunity', models.IntegerField(blank=True, help_text='Opportunity criteria (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, help_text='Computed total score', max_digits=4, null=True)),
                ('comments', models.TextField(blank=True, help_text='Evaluator comments')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='applications.application')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['application', 'evaluator'],
                'unique_together': {('application', 'evaluator')},
            },
        ),
    ]
