# Generated by Django 5.0.14 on 2025-12-25 12:16

import django.core.validators
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Auto-generated application code', max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_feasibility_review', 'Under Feasibility Review'), ('rejected_feasibility', 'Rejected - Not Feasible'), ('pending_evaluation', 'Pending Evaluation'), ('under_evaluation', 'Under Evaluation'), ('evaluated', 'Evaluated'), ('accepted', 'Accepted'), ('pending', 'Pending (Waiting List)'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=30)),
                ('brief_description', models.CharField(help_text='One-line description', max_length=100)),
                ('project_title', models.CharField(blank=True, max_length=300)),
                ('project_code', models.CharField(blank=True, max_length=100)),
                ('funding_agency', models.CharField(blank=True, max_length=200)),
                ('project_type', models.CharField(blank=True, choices=[('national_public', 'National Public Competitive Project'), ('international', 'International Project'), ('regional', 'Regional Project'), ('private', 'Private Funding'), ('other', 'Other')], max_length=50)),
                ('has_competitive_funding', models.BooleanField(default=False)),
                ('subject_area', models.CharField(blank=True, choices=[('biology', 'Biology'), ('medicine', 'Medicine'), ('engineering', 'Engineering'), ('chemistry', 'Chemistry'), ('physics', 'Physics'), ('other', 'Other')], max_length=50)),
                ('service_modality', models.CharField(blank=True, choices=[('full_assistance', 'Full Assistance'), ('presential', 'Presential'), ('self_service', 'Self-Service')], max_length=50)),
                ('specialization_area', models.CharField(blank=True, choices=[('clinical', 'Clinical'), ('preclinical', 'Preclinical'), ('radiotracers', 'Radiotracers and Biomarkers')], max_length=50)),
                ('scientific_relevance', models.TextField(blank=True, help_text='Scientific relevance and originality')),
                ('methodology_description', models.TextField(blank=True, help_text='Methodology and experimental design')),
                ('expected_contributions', models.TextField(blank=True, help_text='Expected contributions and results')),
                ('impact_strengths', models.TextField(blank=True, help_text='Impact and strengths')),
                ('socioeconomic_significance', models.TextField(blank=True, help_text='Socioeconomic significance')),
                ('opportunity_criteria', models.TextField(blank=True, help_text='Opportunity criteria and justification')),
                ('technical_feasibility_confirmed', models.BooleanField(default=False, help_text='Confirmed technical feasibility with node')),
                ('uses_animals', models.BooleanField(default=False)),
                ('has_animal_ethics', models.BooleanField(default=False)),
                ('uses_humans', models.BooleanField(default=False)),
                ('has_human_ethics', models.BooleanField(default=False)),
                ('data_consent', models.BooleanField(default=False, help_text='Data processing consent')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, help_text='Average evaluation score', max_digits=4, null=True)),
                ('resolution', models.CharField(blank=True, choices=[('', 'Not Resolved'), ('accepted', 'Accepted'), ('pending', 'Pending (Waiting List)'), ('rejected', 'Rejected')], max_length=20)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_comments', models.TextField(blank=True, help_text='Coordinator comments on resolution')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeasibilityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_feasible', models.BooleanField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['application', 'node'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalApplication',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Auto-generated application code', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_feasibility_review', 'Under Feasibility Review'), ('rejected_feasibility', 'Rejected - Not Feasible'), ('pending_evaluation', 'Pending Evaluation'), ('under_evaluation', 'Under Evaluation'), ('evaluated', 'Evaluated'), ('accepted', 'Accepted'), ('pending', 'Pending (Waiting List)'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=30)),
                ('brief_description', models.CharField(help_text='One-line description', max_length=100)),
                ('project_title', models.CharField(blank=True, max_length=300)),
                ('project_code', models.CharField(blank=True, max_length=100)),
                ('funding_agency', models.CharField(blank=True, max_length=200)),
                ('project_type', models.CharField(blank=True, choices=[('national_public', 'National Public Competitive Project'), ('international', 'International Project'), ('regional', 'Regional Project'), ('private', 'Private Funding'), ('other', 'Other')], max_length=50)),
                ('has_competitive_funding', models.BooleanField(default=False)),
                ('subject_area', models.CharField(blank=True, choices=[('biology', 'Biology'), ('medicine', 'Medicine'), ('engineering', 'Engineering'), ('chemistry', 'Chemistry'), ('physics', 'Physics'), ('other', 'Other')], max_length=50)),
                ('service_modality', models.CharField(blank=True, choices=[('full_assistance', 'Full Assistance'), ('presential', 'Presential'), ('self_service', 'Self-Service')], max_length=50)),
                ('specialization_area', models.CharField(blank=True, choices=[('clinical', 'Clinical'), ('preclinical', 'Preclinical'), ('radiotracers', 'Radiotracers and Biomarkers')], max_length=50)),
                ('scientific_relevance', models.TextField(blank=True, help_text='Scientific relevance and originality')),
                ('methodology_description', models.TextField(blank=True, help_text='Methodology and experimental design')),
                ('expected_contributions', models.TextField(blank=True, help_text='Expected contributions and results')),
                ('impact_strengths', models.TextField(blank=True, help_text='Impact and strengths')),
                ('socioeconomic_significance', models.TextField(blank=True, help_text='Socioeconomic significance')),
                ('opportunity_criteria', models.TextField(blank=True, help_text='Opportunity criteria and justification')),
                ('technical_feasibility_confirmed', models.BooleanField(default=False, help_text='Confirmed technical feasibility with node')),
                ('uses_animals', models.BooleanField(default=False)),
                ('has_animal_ethics', models.BooleanField(default=False)),
                ('uses_humans', models.BooleanField(default=False)),
                ('has_human_ethics', models.BooleanField(default=False)),
                ('data_consent', models.BooleanField(default=False, help_text='Data processing consent')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, help_text='Average evaluation score', max_digits=4, null=True)),
                ('resolution', models.CharField(blank=True, choices=[('', 'Not Resolved'), ('accepted', 'Accepted'), ('pending', 'Pending (Waiting List)'), ('rejected', 'Rejected')], max_length=20)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_comments', models.TextField(blank=True, help_text='Coordinator comments on resolution')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical application',
                'verbose_name_plural': 'historical applications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFeasibilityReview',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_feasible', models.BooleanField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical feasibility review',
                'verbose_name_plural': 'historical feasibility reviews',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRequestedAccess',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('hours_requested', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Requested Access',
                'verbose_name_plural': 'historical Requested Accesses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RequestedAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_requested', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Requested Access',
                'verbose_name_plural': 'Requested Accesses',
                'ordering': ['application', 'equipment'],
            },
        ),
    ]
