# Generated by Django 5.0.14 on 2026-01-05 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('calls', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='calls.call'),
        ),
        migrations.AddField(
            model_name='feasibilityreview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feasibility_reviews', to='applications.application'),
        ),
        migrations.AddField(
            model_name='feasibilityreview',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.node'),
        ),
        migrations.AddField(
            model_name='feasibilityreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feasibility_reviews_conducted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='applicant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='call',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='calls.call'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfeasibilityreview',
            name='application',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='applications.application'),
        ),
        migrations.AddField(
            model_name='historicalfeasibilityreview',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfeasibilityreview',
            name='node',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.node'),
        ),
        migrations.AddField(
            model_name='historicalfeasibilityreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrequestedaccess',
            name='application',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='applications.application'),
        ),
        migrations.AddField(
            model_name='historicalrequestedaccess',
            name='equipment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.equipment'),
        ),
        migrations.AddField(
            model_name='historicalrequestedaccess',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestedaccess',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_access', to='applications.application'),
        ),
        migrations.AddField(
            model_name='requestedaccess',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_requests', to='core.equipment'),
        ),
        migrations.AlterUniqueTogether(
            name='feasibilityreview',
            unique_together={('application', 'node')},
        ),
        migrations.AlterUniqueTogether(
            name='requestedaccess',
            unique_together={('application', 'equipment')},
        ),
    ]
