# Generated by Django 5.0.14 on 2025-12-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='subject_area',
            field=models.CharField(blank=True, choices=[('phy', 'PHY - Physics'), ('che', 'CHE - Chemistry'), ('mat', 'MAT - Materials Science and Technology'), ('ear', 'EAR - Earth Sciences'), ('bio', 'BIO - Biology'), ('med', 'MED - Medicine'), ('agr', 'AGR - Agricultural Sciences'), ('eng', 'ENG - Engineering and Architecture'), ('soc', 'SOC - Social Sciences'), ('eco', 'ECO - Economics'), ('law', 'LAW - Law'), ('hum', 'HUM - Humanities'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='subject_area',
            field=models.CharField(blank=True, choices=[('phy', 'PHY - Physics'), ('che', 'CHE - Chemistry'), ('mat', 'MAT - Materials Science and Technology'), ('ear', 'EAR - Earth Sciences'), ('bio', 'BIO - Biology'), ('med', 'MED - Medicine'), ('agr', 'AGR - Agricultural Sciences'), ('eng', 'ENG - Engineering and Architecture'), ('soc', 'SOC - Social Sciences'), ('eco', 'ECO - Economics'), ('law', 'LAW - Law'), ('hum', 'HUM - Humanities'), ('other', 'Other')], max_length=50),
        ),
    ]
