# Generated by Django 5.0.14 on 2026-01-12 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequestedaccess',
            name='actual_hours_used',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Actual hours used (reported on completion)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='historicalrequestedaccess',
            name='hours_approved',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hours approved/granted (same as requested for Phase 7 simplification)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='requestedaccess',
            name='actual_hours_used',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Actual hours used (reported on completion)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='requestedaccess',
            name='hours_approved',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hours approved/granted (same as requested for Phase 7 simplification)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='historicalrequestedaccess',
            name='hours_requested',
            field=models.DecimalField(decimal_places=1, help_text='Hours requested by applicant', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='requestedaccess',
            name='hours_requested',
            field=models.DecimalField(decimal_places=1, help_text='Hours requested by applicant', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
