# Generated by Django 5.0.14 on 2026-01-13 10:28

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequestedaccess',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When this equipment access was marked as completed', null=True),
        ),
        migrations.AddField(
            model_name='historicalrequestedaccess',
            name='completed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who marked this equipment access as completed', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrequestedaccess',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Equipment access marked as completed (by either applicant or node coordinator)'),
        ),
        migrations.AddField(
            model_name='historicalrequestedaccess',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestedaccess',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When this equipment access was marked as completed', null=True),
        ),
        migrations.AddField(
            model_name='requestedaccess',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='User who marked this equipment access as completed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_equipment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestedaccess',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Equipment access marked as completed (by either applicant or node coordinator)'),
        ),
        migrations.AddField(
            model_name='requestedaccess',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='HistoricalNodeResolution',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('resolution', models.CharField(blank=True, choices=[('', 'Not Decided'), ('accept', 'Accept'), ('waitlist', 'Waitlist'), ('reject', 'Reject')], help_text="This node's resolution decision", max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Node coordinator comments on resolution')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When node coordinator made their decision', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('application', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='applications.application')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, db_constraint=False, help_text='Node providing this resolution', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.node')),
                ('reviewer', models.ForeignKey(blank=True, db_constraint=False, help_text='Node coordinator who made this decision', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Node Resolution',
                'verbose_name_plural': 'historical Node Resolutions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NodeResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(blank=True, choices=[('', 'Not Decided'), ('accept', 'Accept'), ('waitlist', 'Waitlist'), ('reject', 'Reject')], help_text="This node's resolution decision", max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Node coordinator comments on resolution')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When node coordinator made their decision', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_resolutions', to='applications.application')),
                ('node', models.ForeignKey(help_text='Node providing this resolution', on_delete=django.db.models.deletion.PROTECT, to='core.node')),
                ('reviewer', models.ForeignKey(help_text='Node coordinator who made this decision', on_delete=django.db.models.deletion.PROTECT, related_name='node_resolutions_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Node Resolution',
                'verbose_name_plural': 'Node Resolutions',
                'ordering': ['application', 'node'],
                'unique_together': {('application', 'node')},
            },
        ),
    ]
