# Generated by Django 5.0.14 on 2026-01-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrequestedaccess',
            name='hours_granted',
        ),
        migrations.RemoveField(
            model_name='requestedaccess',
            name='hours_granted',
        ),
    ]
