# Generated by Django 5.0.14 on 2025-12-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_subject_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_email',
            field=models.EmailField(blank=True, help_text='Contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_entity',
            field=models.CharField(blank=True, help_text='Institution/organization', max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_name',
            field=models.CharField(blank=True, help_text='Auto-filled from user profile', max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_orcid',
            field=models.CharField(blank=True, help_text='Optional ORCID identifier', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_phone',
            field=models.CharField(blank=True, help_text='Contact phone', max_length=30),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='applicant_email',
            field=models.EmailField(blank=True, help_text='Contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='applicant_entity',
            field=models.CharField(blank=True, help_text='Institution/organization', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='applicant_name',
            field=models.CharField(blank=True, help_text='Auto-filled from user profile', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='applicant_orcid',
            field=models.CharField(blank=True, help_text='Optional ORCID identifier', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='applicant_phone',
            field=models.CharField(blank=True, help_text='Contact phone', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='project_type',
            field=models.CharField(blank=True, choices=[('national', 'National'), ('international_non_european', 'International, non-European'), ('regional', 'Regional'), ('european', 'European'), ('internal', 'Internal'), ('private', 'Private'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='subject_area',
            field=models.CharField(blank=True, choices=[('cso', 'CSO - Social Sciences'), ('der', 'DER - Law'), ('eco', 'ECO - Economy'), ('mlp', 'MLP - Mind, language and thought'), ('fla', 'FLA - Culture: Philology, literature and art'), ('pha', 'PHA - Studies in history and archaeology'), ('edu', 'EDU - Educational Sciences'), ('psi', 'PSI - Psychology'), ('mtm', 'MTM - Mathematical Sciences'), ('fis', 'FIS - Physical Sciences'), ('pin', 'PIN - Industrial production, engineering'), ('tic', 'TIC - Information and communications technologies'), ('eyt', 'EYT - Energy and Transport'), ('ctq', 'CTQ - Chemical sciences and technologies'), ('mat', 'MAT - Materials Sciences and Technology'), ('ctm', 'CTM - Environmental science and technology'), ('caa', 'CAA - Agricultural sciences'), ('bio', 'BIO - Biosciences and biotechnology'), ('bme', 'BME - Biomedicine'), ('other', 'Other (specify)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='project_type',
            field=models.CharField(blank=True, choices=[('national', 'National'), ('international_non_european', 'International, non-European'), ('regional', 'Regional'), ('european', 'European'), ('internal', 'Internal'), ('private', 'Private'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='subject_area',
            field=models.CharField(blank=True, choices=[('cso', 'CSO - Social Sciences'), ('der', 'DER - Law'), ('eco', 'ECO - Economy'), ('mlp', 'MLP - Mind, language and thought'), ('fla', 'FLA - Culture: Philology, literature and art'), ('pha', 'PHA - Studies in history and archaeology'), ('edu', 'EDU - Educational Sciences'), ('psi', 'PSI - Psychology'), ('mtm', 'MTM - Mathematical Sciences'), ('fis', 'FIS - Physical Sciences'), ('pin', 'PIN - Industrial production, engineering'), ('tic', 'TIC - Information and communications technologies'), ('eyt', 'EYT - Energy and Transport'), ('ctq', 'CTQ - Chemical sciences and technologies'), ('mat', 'MAT - Materials Sciences and Technology'), ('ctm', 'CTM - Environmental science and technology'), ('caa', 'CAA - Agricultural sciences'), ('bio', 'BIO - Biosciences and biotechnology'), ('bme', 'BME - Biomedicine'), ('other', 'Other (specify)')], max_length=50),
        ),
    ]
