# Generated by Django 5.0.14 on 2026-01-15 08:27

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_add_node_resolution_and_completion_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='signature_affirmation',
            field=models.BooleanField(default=False, help_text='User affirmed valid electronic signature'),
        ),
        migrations.AddField(
            model_name='application',
            name='signed_pdf',
            field=models.FileField(blank=True, help_text='Uploaded PDF with electronic signature', null=True, upload_to=applications.models.signed_pdf_upload_path),
        ),
        migrations.AddField(
            model_name='application',
            name='signed_pdf_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='signature_affirmation',
            field=models.BooleanField(default=False, help_text='User affirmed valid electronic signature'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='signed_pdf',
            field=models.TextField(blank=True, help_text='Uploaded PDF with electronic signature', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='signed_pdf_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
