# Generated by Django 5.0.14 on 2026-02-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_add_signed_pdf_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='specialization_area',
            field=models.CharField(blank=True, choices=[('clinical', 'Clinical'), ('preclinical', 'Preclinical'), ('radiotracers', 'Radiotracers'), ('radiochemistry', 'Radiochemistry Lab')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='specialization_area',
            field=models.CharField(blank=True, choices=[('clinical', 'Clinical'), ('preclinical', 'Preclinical'), ('radiotracers', 'Radiotracers'), ('radiochemistry', 'Radiochemistry Lab')], max_length=50),
        ),
    ]
