# Generated by Django 5.0.14 on 2025-12-31 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_applicant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequestedaccess',
            name='hours_granted',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hours allocated during resolution (Phase 6)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='requestedaccess',
            name='hours_granted',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hours allocated during resolution (Phase 6)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
