# Generated by Django 5.0.14 on 2026-02-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_align_specialization_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='specialization_area',
            field=models.CharField(blank=True, choices=[('clinical', 'Clinical'), ('preclinical', 'Preclinical'), ('radiochemistry', 'Radiochemistry')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='specialization_area',
            field=models.CharField(blank=True, choices=[('clinical', 'Clinical'), ('preclinical', 'Preclinical'), ('radiochemistry', 'Radiochemistry')], max_length=50),
        ),
    ]
