# Generated by Django 5.0.14 on 2025-12-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_add_hours_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='acceptance_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for applicant to respond (resolution_date + 10 days)', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='When applicant accepted or declined', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='accepted_by_applicant',
            field=models.BooleanField(blank=True, help_text='Applicant acceptance: True=accepted, False=declined, None=pending', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Optional: When marked as completed', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='handoff_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When handoff email was sent to applicant + coordinators', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Optional: Mark as completed for reporting purposes'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='acceptance_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for applicant to respond (resolution_date + 10 days)', null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='When applicant accepted or declined', null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='accepted_by_applicant',
            field=models.BooleanField(blank=True, help_text='Applicant acceptance: True=accepted, False=declined, None=pending', null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Optional: When marked as completed', null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='handoff_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When handoff email was sent to applicant + coordinators', null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Optional: Mark as completed for reporting purposes'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_feasibility_review', 'Under Feasibility Review'), ('rejected_feasibility', 'Rejected - Not Feasible'), ('pending_evaluation', 'Pending Evaluation'), ('under_evaluation', 'Under Evaluation'), ('evaluated', 'Evaluated'), ('accepted', 'Accepted'), ('pending', 'Pending (Waiting List)'), ('rejected', 'Rejected'), ('declined_by_applicant', 'Declined by Applicant'), ('expired', 'Acceptance Expired')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_feasibility_review', 'Under Feasibility Review'), ('rejected_feasibility', 'Rejected - Not Feasible'), ('pending_evaluation', 'Pending Evaluation'), ('under_evaluation', 'Under Evaluation'), ('evaluated', 'Evaluated'), ('accepted', 'Accepted'), ('pending', 'Pending (Waiting List)'), ('rejected', 'Rejected'), ('declined_by_applicant', 'Declined by Applicant'), ('expired', 'Acceptance Expired')], default='draft', max_length=30),
        ),
    ]
