# Generated by Django 5.0.14 on 2026-04-01 14:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_application_specialization_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'funding agencies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='project_name',
            field=models.CharField(blank=True, help_text='Name of the research project', max_length=300),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='project_name',
            field=models.CharField(blank=True, help_text='Name of the research project', max_length=300),
        ),
        migrations.AlterField(
            model_name='application',
            name='funding_agency',
            field=models.CharField(blank=True, help_text='Legacy text field', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='project_title',
            field=models.CharField(blank=True, help_text='Name of the funded project', max_length=300),
        ),
        migrations.AlterField(
            model_name='application',
            name='project_type',
            field=models.CharField(blank=True, choices=[('national', 'National (Spain)'), ('regional', 'Regional (Autonomous Communities)'), ('european', 'European Union (EU)'), ('international_non_european', 'International (non-EU)'), ('internal', 'Internal / Institutional'), ('private', 'Private'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_feasibility_review', 'Under Feasibility Review'), ('rejected_feasibility', 'Rejected - Not Feasible'), ('pending_evaluation', 'Pending Evaluation'), ('under_evaluation', 'Under Evaluation'), ('evaluated', 'Evaluated'), ('accepted', 'Accepted'), ('pending', 'Pending (Waiting List)'), ('rejected', 'Rejected'), ('declined_by_applicant', 'Declined by Applicant'), ('expired', 'Acceptance Expired'), ('completed', 'Completed')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='funding_agency',
            field=models.CharField(blank=True, help_text='Legacy text field', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='project_title',
            field=models.CharField(blank=True, help_text='Name of the funded project', max_length=300),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='project_type',
            field=models.CharField(blank=True, choices=[('national', 'National (Spain)'), ('regional', 'Regional (Autonomous Communities)'), ('european', 'European Union (EU)'), ('international_non_european', 'International (non-EU)'), ('internal', 'Internal / Institutional'), ('private', 'Private'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_feasibility_review', 'Under Feasibility Review'), ('rejected_feasibility', 'Rejected - Not Feasible'), ('pending_evaluation', 'Pending Evaluation'), ('under_evaluation', 'Under Evaluation'), ('evaluated', 'Evaluated'), ('accepted', 'Accepted'), ('pending', 'Pending (Waiting List)'), ('rejected', 'Rejected'), ('declined_by_applicant', 'Declined by Applicant'), ('expired', 'Acceptance Expired'), ('completed', 'Completed')], default='draft', max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='funding_agency_obj',
            field=models.ForeignKey(blank=True, help_text='Funding agency from DB list', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.fundingagency'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='funding_agency_obj',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Funding agency from DB list', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='applications.fundingagency'),
        ),
        migrations.CreateModel(
            name='HistoricalFundingAgency',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical funding agency',
                'verbose_name_plural': 'historical funding agencies',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
