# Generated by Django 5.0.14 on 2026-04-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_fundingagency_application_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feasibilityreview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edits_requested', 'Edits Requested')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalfeasibilityreview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edits_requested', 'Edits Requested')], default='pending', max_length=20),
        ),
    ]
