# Generated by Django 5.0.14 on 2026-04-01 15:13

from django.db import migrations


def populate_status_from_is_feasible(apps, schema_editor):
    """Populate the new status field from the legacy is_feasible field."""
    FeasibilityReview = apps.get_model('applications', 'FeasibilityReview')
    for review in FeasibilityReview.objects.all():
        if review.is_feasible is True:
            review.status = 'approved'
        elif review.is_feasible is False:
            review.status = 'rejected'
        else:
            review.status = 'pending'
        review.save(update_fields=['status'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_feasibilityreview_status_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_status_from_is_feasible, reverse_noop),
    ]
