# Generated by Django 5.0.14 on 2026-04-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_populate_feasibility_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingagency',
            name='origin_of_funds',
            field=models.CharField(blank=True, choices=[('spanish_government', 'Spanish Government'), ('international_non_eu', 'International / Non-EU'), ('spanish_regional', 'Spanish Regional Government'), ('european_union', 'European Union'), ('institutional', 'Institutional / Internal'), ('private', 'Private / Philanthropic'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='historicalfundingagency',
            name='origin_of_funds',
            field=models.CharField(blank=True, choices=[('spanish_government', 'Spanish Government'), ('international_non_eu', 'International / Non-EU'), ('spanish_regional', 'Spanish Regional Government'), ('european_union', 'European Union'), ('institutional', 'Institutional / Internal'), ('private', 'Private / Philanthropic'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='project_type',
            field=models.CharField(blank=True, choices=[('spanish_government', 'Spanish Government'), ('international_non_eu', 'International / Non-EU'), ('spanish_regional', 'Spanish Regional Government'), ('european_union', 'European Union'), ('institutional', 'Institutional / Internal'), ('private', 'Private / Philanthropic'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='project_type',
            field=models.CharField(blank=True, choices=[('spanish_government', 'Spanish Government'), ('international_non_eu', 'International / Non-EU'), ('spanish_regional', 'Spanish Regional Government'), ('european_union', 'European Union'), ('institutional', 'Institutional / Internal'), ('private', 'Private / Philanthropic'), ('other', 'Other')], max_length=50),
        ),
    ]
