# Generated by Django 5.0.14 on 2026-04-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_fundingagency_origin_of_funds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='historicalapplication',
            name='project_title',
        ),
    ]
