# Generated by Django 5.0.14 on 2026-04-15 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_remove_application_project_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='has_informed_consent',
            field=models.BooleanField(default=False, help_text='Informed consent protocol in place for human subjects work'),
        ),
        migrations.AddField(
            model_name='application',
            name='has_insurance',
            field=models.BooleanField(default=False, help_text='Civil liability insurance in place for human subjects work'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='has_informed_consent',
            field=models.BooleanField(default=False, help_text='Informed consent protocol in place for human subjects work'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='has_insurance',
            field=models.BooleanField(default=False, help_text='Civil liability insurance in place for human subjects work'),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_orcid',
            field=models.CharField(blank=True, help_text='Optional ORCID identifier (XXXX-XXXX-XXXX-XXXX)', max_length=20, validators=[django.core.validators.RegexValidator(message='ORCID iD must be in the format XXXX-XXXX-XXXX-XXXX (last character may be X).', regex='^\\d{4}-\\d{4}-\\d{4}-\\d{3}[\\dX]$')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant_phone',
            field=models.CharField(blank=True, help_text='Contact phone', max_length=30, validators=[django.core.validators.RegexValidator(message='Phone numbers may contain only digits, spaces, and the characters + - . ( ).', regex='^[\\d\\s()+\\-.]{5,}$')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='expected_contributions',
            field=models.TextField(blank=True, help_text='Expected contributions and results', max_length=5000),
        ),
        migrations.AlterField(
            model_name='application',
            name='impact_strengths',
            field=models.TextField(blank=True, help_text='Impact and strengths', max_length=5000),
        ),
        migrations.AlterField(
            model_name='application',
            name='methodology_description',
            field=models.TextField(blank=True, help_text='Methodology and experimental design', max_length=5000),
        ),
        migrations.AlterField(
            model_name='application',
            name='opportunity_criteria',
            field=models.TextField(blank=True, help_text='Opportunity criteria and justification', max_length=5000),
        ),
        migrations.AlterField(
            model_name='application',
            name='scientific_relevance',
            field=models.TextField(blank=True, help_text='Scientific relevance and originality', max_length=5000),
        ),
        migrations.AlterField(
            model_name='application',
            name='socioeconomic_significance',
            field=models.TextField(blank=True, help_text='Socioeconomic significance', max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='applicant_orcid',
            field=models.CharField(blank=True, help_text='Optional ORCID identifier (XXXX-XXXX-XXXX-XXXX)', max_length=20, validators=[django.core.validators.RegexValidator(message='ORCID iD must be in the format XXXX-XXXX-XXXX-XXXX (last character may be X).', regex='^\\d{4}-\\d{4}-\\d{4}-\\d{3}[\\dX]$')]),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='applicant_phone',
            field=models.CharField(blank=True, help_text='Contact phone', max_length=30, validators=[django.core.validators.RegexValidator(message='Phone numbers may contain only digits, spaces, and the characters + - . ( ).', regex='^[\\d\\s()+\\-.]{5,}$')]),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='expected_contributions',
            field=models.TextField(blank=True, help_text='Expected contributions and results', max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='impact_strengths',
            field=models.TextField(blank=True, help_text='Impact and strengths', max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='methodology_description',
            field=models.TextField(blank=True, help_text='Methodology and experimental design', max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='opportunity_criteria',
            field=models.TextField(blank=True, help_text='Opportunity criteria and justification', max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='scientific_relevance',
            field=models.TextField(blank=True, help_text='Scientific relevance and originality', max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='socioeconomic_significance',
            field=models.TextField(blank=True, help_text='Socioeconomic significance', max_length=5000),
        ),
    ]
