# Generated by Django 5.0.14 on 2026-05-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_application_has_informed_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='consult_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the applicant requested a feasibility consult from step 5.', null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='consult_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the applicant requested a feasibility consult from step 5.', null=True),
        ),
    ]
