# Generated by Django 5.0.14 on 2026-08-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_application_consult_requested_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_feasibility_review', 'Under Feasibility Review'), ('rejected_feasibility', 'Rejected - Not Feasible'), ('pending_evaluation', 'Pending Evaluation'), ('under_evaluation', 'Under Evaluation'), ('evaluated', 'Evaluated'), ('accepted', 'Accepted'), ('pending', 'Pending (Waiting List)'), ('rejected', 'Rejected'), ('declined_by_applicant', 'Declined by Applicant'), ('expired', 'Acceptance Expired'), ('completed', 'Completed'), ('not_reached', 'Not Reached This Call')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_feasibility_review', 'Under Feasibility Review'), ('rejected_feasibility', 'Rejected - Not Feasible'), ('pending_evaluation', 'Pending Evaluation'), ('under_evaluation', 'Under Evaluation'), ('evaluated', 'Evaluated'), ('accepted', 'Accepted'), ('pending', 'Pending (Waiting List)'), ('rejected', 'Rejected'), ('declined_by_applicant', 'Declined by Applicant'), ('expired', 'Acceptance Expired'), ('completed', 'Completed'), ('not_reached', 'Not Reached This Call')], default='draft', max_length=30),
        ),
    ]
