# Generated by Django 5.0.14 on 2026-09-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='execution_end',
            field=models.DateTimeField(blank=True, help_text="Node-set end of this project's execution period. Empty means the call's execution_end applies.", null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='execution_end',
            field=models.DateTimeField(blank=True, help_text="Node-set end of this project's execution period. Empty means the call's execution_end applies.", null=True),
        ),
    ]
