# Generated by Django 5.0.14 on 2025-12-25 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnode',
            name='director',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Node director/coordinator', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='node',
            name='director',
            field=models.ForeignKey(blank=True, help_text='Node director/coordinator', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directed_nodes', to=settings.AUTH_USER_MODEL),
        ),
    ]
