# Generated by Django 5.0.14 on 2026-02-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserrole',
            name='area',
            field=models.CharField(blank=True, choices=[('', 'Not applicable'), ('clinical', 'Clinical'), ('preclinical', 'Preclinical'), ('radiotracers', 'Radiotracers'), ('radiochemistry', 'Radiochemistry Lab')], help_text='Specialization area for evaluators', max_length=50),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='area',
            field=models.CharField(blank=True, choices=[('', 'Not applicable'), ('clinical', 'Clinical'), ('preclinical', 'Preclinical'), ('radiotracers', 'Radiotracers'), ('radiochemistry', 'Radiochemistry Lab')], help_text='Specialization area for evaluators', max_length=50),
        ),
    ]
