# Generated by Django 5.0.14 on 2025-12-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicalnode_director_node_director'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
