# Generated by Django 5.0.14 on 2026-02-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_align_specialization_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserrole',
            name='area',
            field=models.CharField(blank=True, choices=[('', 'Not applicable'), ('clinical', 'Clinical'), ('preclinical', 'Preclinical'), ('radiochemistry', 'Radiochemistry')], help_text='Specialization area for evaluators', max_length=50),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='area',
            field=models.CharField(blank=True, choices=[('', 'Not applicable'), ('clinical', 'Clinical'), ('preclinical', 'Preclinical'), ('radiochemistry', 'Radiochemistry')], help_text='Specialization area for evaluators', max_length=50),
        ),
    ]
