# Generated by Django 5.0.14 on 2026-04-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_historicaluserrole_area_alter_userrole_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='vat',
            field=models.CharField(blank=True, help_text='VAT/NIF number', max_length=50),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='auto_data_consent',
            field=models.BooleanField(default=False, help_text='Automatic data processing consent for all future applications'),
        ),
        migrations.AddField(
            model_name='organization',
            name='vat',
            field=models.CharField(blank=True, help_text='VAT/NIF number', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='auto_data_consent',
            field=models.BooleanField(default=False, help_text='Automatic data processing consent for all future applications'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('mri', 'MRI'), ('pet', 'PET'), ('ct', 'CT'), ('pet_ct', 'PET-CT'), ('pet_mri', 'PET-MRI'), ('spect_pet_ct', 'SPECT-PET-CT'), ('spect_pet_ct_oi', 'SPECT-PET-CT-OI'), ('cyclotron', 'Cyclotron'), ('spect', 'SPECT'), ('ultrasound', 'Ultrasound'), ('optical', 'Optical Imaging'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='category',
            field=models.CharField(choices=[('mri', 'MRI'), ('pet', 'PET'), ('ct', 'CT'), ('pet_ct', 'PET-CT'), ('pet_mri', 'PET-MRI'), ('spect_pet_ct', 'SPECT-PET-CT'), ('spect_pet_ct_oi', 'SPECT-PET-CT-OI'), ('cyclotron', 'Cyclotron'), ('spect', 'SPECT'), ('ultrasound', 'Ultrasound'), ('optical', 'Optical Imaging'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='organization_type',
            field=models.CharField(choices=[('company', 'Company / Empresa'), ('university', 'University / Universidad'), ('other', 'Other / Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('company', 'Company / Empresa'), ('university', 'University / Universidad'), ('other', 'Other / Otro')], max_length=50),
        ),
    ]
