# Generated by Django 5.0.14 on 2026-04-01 15:08

from django.db import migrations


def remap_org_types(apps, schema_editor):
    """Remap old organization types to the new 3-choice set."""
    Organization = apps.get_model('core', 'Organization')
    # research_center, hospital, ministry -> other
    Organization.objects.filter(
        organization_type__in=['research_center', 'hospital', 'ministry']
    ).update(organization_type='other')


def reverse_noop(apps, schema_editor):
    pass  # Cannot reliably reverse the remap


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historicalorganization_vat_and_more'),
    ]

    operations = [
        migrations.RunPython(remap_org_types, reverse_noop),
    ]
