# Generated by Django 5.0.14 on 2026-04-07 09:18
# Manually edited to:
#   1. Rename `area` -> `areas` (preserves existing values)
#   2. Alter field to drop `choices` and increase `max_length` to 200
#   3. Apply same changes to historical model

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remap_organization_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='area',
            new_name='areas',
        ),
        migrations.RenameField(
            model_name='historicaluserrole',
            old_name='area',
            new_name='areas',
        ),
        migrations.AlterField(
            model_name='userrole',
            name='areas',
            field=models.CharField(
                blank=True,
                help_text='Comma-separated specialization areas for evaluators (e.g. "clinical,preclinical")',
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name='historicaluserrole',
            name='areas',
            field=models.CharField(
                blank=True,
                help_text='Comma-separated specialization areas for evaluators (e.g. "clinical,preclinical")',
                max_length=200,
            ),
        ),
    ]
