# Generated by Django 5.0.14 on 2026-04-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_historicaluserrole_area_remove_userrole_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserrole',
            name='areas',
            field=models.CharField(blank=True, help_text='Semicolon-separated specialization areas for evaluators (e.g. "clinical;preclinical")', max_length=200),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='areas',
            field=models.CharField(blank=True, help_text='Semicolon-separated specialization areas for evaluators (e.g. "clinical;preclinical")', max_length=200),
        ),
    ]
