# Generated by Django 5.0.14 on 2026-04-15 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_historicaluserrole_areas_alter_userrole_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='orcid',
            field=models.CharField(blank=True, help_text='ORCID iD in the format XXXX-XXXX-XXXX-XXXX', max_length=20, validators=[django.core.validators.RegexValidator(message='ORCID iD must be in the format XXXX-XXXX-XXXX-XXXX (last character may be X).', regex='^\\d{4}-\\d{4}-\\d{4}-\\d{3}[\\dX]$')]),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Phone numbers may contain only digits, spaces, and the characters + - . ( ).', regex='^[\\d\\s()+\\-.]{5,}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='orcid',
            field=models.CharField(blank=True, help_text='ORCID iD in the format XXXX-XXXX-XXXX-XXXX', max_length=20, validators=[django.core.validators.RegexValidator(message='ORCID iD must be in the format XXXX-XXXX-XXXX-XXXX (last character may be X).', regex='^\\d{4}-\\d{4}-\\d{4}-\\d{3}[\\dX]$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Phone numbers may contain only digits, spaces, and the characters + - . ( ).', regex='^[\\d\\s()+\\-.]{5,}$')]),
        ),
    ]
