# Generated by Django 5.0.14 on 2026-04-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_historicaluser_orcid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorganization',
            name='website',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='website',
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='iso2',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code (e.g. ES, FR, US). Required for TSV-imported records; may be blank for self-service entries.', max_length=2),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='short_name',
            field=models.CharField(blank=True, help_text='Acronym / short display name', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='zip',
            field=models.CharField(blank=True, help_text='Postal code', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='iso2',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code (e.g. ES, FR, US). Required for TSV-imported records; may be blank for self-service entries.', max_length=2),
        ),
        migrations.AddField(
            model_name='organization',
            name='short_name',
            field=models.CharField(blank=True, help_text='Acronym / short display name', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='zip',
            field=models.CharField(blank=True, help_text='Postal code', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='organization_type',
            field=models.CharField(choices=[('technology_centre', 'Technology Centre'), ('pro', 'Public Research Organisation (PRO)'), ('hei', 'Higher Education Institution (HEI)'), ('sme', 'SME'), ('large_enterprise', 'Large Enterprise'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('technology_centre', 'Technology Centre'), ('pro', 'Public Research Organisation (PRO)'), ('hei', 'Higher Education Institution (HEI)'), ('sme', 'SME'), ('large_enterprise', 'Large Enterprise'), ('other', 'Other')], max_length=50),
        ),
    ]
