# Generated by Django 5.0.14 on 2026-04-16 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reshape_organization_for_real_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnode',
            name='name',
        ),
        migrations.RemoveField(
            model_name='node',
            name='name',
        ),
        migrations.AddField(
            model_name='historicalnode',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Host institution. The display name comes from organization.name.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.organization'),
        ),
        migrations.AddField(
            model_name='node',
            name='organization',
            field=models.ForeignKey(default=1, help_text='Host institution. The display name comes from organization.name.', on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='core.organization'),
            preserve_default=False,
        ),
    ]
