# Generated by Django 5.0.14 on 2026-04-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_promote_node_to_org_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='area',
            field=models.CharField(blank=True, choices=[('preclinical', 'Preclinical'), ('clinical', 'Clinical'), ('radiochemistry', 'Radiochemistry')], help_text='Specialization area for evaluator-matching', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='area',
            field=models.CharField(blank=True, choices=[('preclinical', 'Preclinical'), ('clinical', 'Clinical'), ('radiochemistry', 'Radiochemistry')], help_text='Specialization area for evaluator-matching', max_length=20),
        ),
    ]
