# Generated by Django 5.0.14 on 2025-12-25 12:16

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., COA-2025-01', max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for Submissions'), ('closed', 'Closed - Under Evaluation'), ('resolved', 'Resolved')], default='draft', max_length=20)),
                ('submission_start', models.DateTimeField()),
                ('submission_end', models.DateTimeField()),
                ('evaluation_deadline', models.DateTimeField()),
                ('execution_start', models.DateTimeField(help_text='When experiments can begin')),
                ('execution_end', models.DateTimeField(help_text='When experiments must end')),
                ('description', models.TextField(help_text='Call description (HTML allowed)')),
                ('guidelines', models.TextField(blank=True, help_text='Application guidelines')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'COA Call',
                'ordering': ['-submission_start'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCall',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='e.g., COA-2025-01', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for Submissions'), ('closed', 'Closed - Under Evaluation'), ('resolved', 'Resolved')], default='draft', max_length=20)),
                ('submission_start', models.DateTimeField()),
                ('submission_end', models.DateTimeField()),
                ('evaluation_deadline', models.DateTimeField()),
                ('execution_start', models.DateTimeField(help_text='When experiments can begin')),
                ('execution_end', models.DateTimeField(help_text='When experiments must end')),
                ('description', models.TextField(help_text='Call description (HTML allowed)')),
                ('guidelines', models.TextField(blank=True, help_text='Application guidelines')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical COA Call',
                'verbose_name_plural': 'historical COA Calls',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCallEquipmentAllocation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('hours_offered', models.DecimalField(decimal_places=1, help_text='Total hours available for this call', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Equipment Allocation',
                'verbose_name_plural': 'historical Equipment Allocations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CallEquipmentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_offered', models.DecimalField(decimal_places=1, help_text='Total hours available for this call', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_allocations', to='calls.call')),
            ],
            options={
                'verbose_name': 'Equipment Allocation',
                'ordering': ['call', 'equipment'],
            },
        ),
    ]
