# Generated by Django 5.0.14 on 2026-01-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callequipmentallocation',
            name='hours_offered',
        ),
        migrations.RemoveField(
            model_name='historicalcallequipmentallocation',
            name='hours_offered',
        ),
    ]
