# Generated by Django 5.0.14 on 2025-12-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='is_resolution_locked',
            field=models.BooleanField(default=False, help_text='Prevent resolution changes after finalization (Phase 6)'),
        ),
        migrations.AddField(
            model_name='historicalcall',
            name='is_resolution_locked',
            field=models.BooleanField(default=False, help_text='Prevent resolution changes after finalization (Phase 6)'),
        ),
    ]
