# Generated by Django 5.0.14 on 2026-08-17 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_initial'),
        ('core', '0011_add_equipment_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('announced', 'Announced - Opens Soon'), ('open', 'Open for Submissions'), ('closed', 'Closed - Under Evaluation'), ('resolved', 'Resolved')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcall',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('announced', 'Announced - Opens Soon'), ('open', 'Open for Submissions'), ('closed', 'Closed - Under Evaluation'), ('resolved', 'Resolved')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ConsultRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emails_sent_at', models.DateTimeField(blank=True, help_text='When the coordinator notifications were dispatched', null=True)),
                ('ip_hash', models.CharField(blank=True, help_text='SHA-256 of the submitting IP, for abuse follow-up only', max_length=64)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consult_requests', to='calls.call')),
                ('equipment', models.ManyToManyField(help_text='Equipment on this call the requester asked about', related_name='consult_requests', to='core.equipment')),
                ('user', models.ForeignKey(blank=True, help_text='Set when the requester was logged in; anonymous otherwise', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consult_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consult Request',
                'ordering': ['-created_at'],
            },
        ),
    ]
