# Generated by Django 5.0.14 on 2026-08-21 08:28

from django.db import migrations, models
from django.utils import timezone


def backfill_resolutions_released(apps, schema_editor):
    """Grandfather calls whose resolutions already went out.

    Only calls with at least one application that already has a non-blank
    `resolution` are marked released — NOT every existing call. A call that
    is merely `closed`/`resolved` with no resolutions yet (e.g. the October
    2026 call, which may already exist as a `draft` when this deploys) must
    stay gated so the release action is meaningful for it.
    """
    Call = apps.get_model('calls', 'Call')
    now = timezone.now()
    Call.objects.filter(
        applications__resolution__gt=''
    ).distinct().update(
        resolutions_released=True,
        resolutions_released_at=now,
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_alter_call_status_alter_historicalcall_status_and_more'),
        ('applications', '0014_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='resolutions_released',
            field=models.BooleanField(default=False, help_text='Node coordinators can only resolve applications once this is set'),
        ),
        migrations.AddField(
            model_name='call',
            name='resolutions_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcall',
            name='resolutions_released',
            field=models.BooleanField(default=False, help_text='Node coordinators can only resolve applications once this is set'),
        ),
        migrations.AddField(
            model_name='historicalcall',
            name='resolutions_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_resolutions_released, noop),
    ]
