# Generated by Django 5.0.14 on 2026-05-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL slug, e.g. "spring-2026". Used in /newsletters/<slug>/.', max_length=200, unique=True)),
                ('publish_date', models.DateField(help_text='Date displayed on the listing.')),
                ('summary', models.TextField(help_text='One- or two-line teaser shown on the newsletter index.')),
                ('html_file', models.FileField(help_text='Self-contained HTML file (inline CSS, no external assets).', upload_to='newsletters/')),
                ('is_published', models.BooleanField(default=False, help_text='Unpublished newsletters are hidden from the public list.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
    ]
