# Generated by Django 5.0.6 on 2026-01-12 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('call_summary', 'Call Summary Report'), ('node_statistics', 'Node Usage Statistics'), ('ministry_annual', 'Ministry Annual Report'), ('equipment_utilization', 'Equipment Utilization Report'), ('publication_outcomes', 'Publication Outcomes Report'), ('user_activity', 'User Activity Report')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('file_path', models.FileField(blank=True, upload_to='reports/%Y/%m/')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('parameters_json', models.JSONField(default=dict, help_text='Report generation parameters')),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calls.call')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.node')),
            ],
            options={
                'verbose_name': 'Report Generation',
                'ordering': ['-generated_at'],
            },
        ),
    ]
