# Generated by Django 5.0.6 on 2026-01-01 11:49

import django.core.validators
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_granted', models.DecimalField(decimal_places=1, help_text='Hours approved for this equipment', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('scheduled_start', models.DateField(blank=True, null=True)),
                ('scheduled_end', models.DateField(blank=True, null=True)),
                ('accepted_by_user', models.BooleanField(blank=True, help_text='User accepted the grant', null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_deadline', models.DateTimeField(blank=True, help_text='Deadline for user to accept', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_hours_used', models.DecimalField(blank=True, decimal_places=1, help_text='Actual hours used (reported by node)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Access Grant',
                'ordering': ['application', 'equipment'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAccessGrant',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('hours_granted', models.DecimalField(decimal_places=1, help_text='Hours approved for this equipment', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('scheduled_start', models.DateField(blank=True, null=True)),
                ('scheduled_end', models.DateField(blank=True, null=True)),
                ('accepted_by_user', models.BooleanField(blank=True, help_text='User accepted the grant', null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_deadline', models.DateTimeField(blank=True, help_text='Deadline for user to accept', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_hours_used', models.DecimalField(blank=True, decimal_places=1, help_text='Actual hours used (reported by node)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Access Grant',
                'verbose_name_plural': 'historical Access Grants',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPublication',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField(blank=True, help_text='List of authors')),
                ('doi', models.CharField(blank=True, help_text='Digital Object Identifier', max_length=100)),
                ('journal', models.CharField(blank=True, max_length=200)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('redib_acknowledged', models.BooleanField(default=False, help_text='ReDIB properly acknowledged in publication')),
                ('acknowledgment_text', models.TextField(blank=True, help_text='Acknowledgment text found in publication')),
                ('citations', models.IntegerField(blank=True, help_text='Number of citations (if tracked)', null=True)),
                ('impact_factor', models.DecimalField(blank=True, decimal_places=3, help_text='Journal impact factor', max_digits=6, null=True)),
                ('reported_at', models.DateTimeField(blank=True, editable=False)),
                ('verified', models.BooleanField(default=False, help_text='Verified by coordinator')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical publication',
                'verbose_name_plural': 'historical publications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField(blank=True, help_text='List of authors')),
                ('doi', models.CharField(blank=True, help_text='Digital Object Identifier', max_length=100)),
                ('journal', models.CharField(blank=True, max_length=200)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('redib_acknowledged', models.BooleanField(default=False, help_text='ReDIB properly acknowledged in publication')),
                ('acknowledgment_text', models.TextField(blank=True, help_text='Acknowledgment text found in publication')),
                ('citations', models.IntegerField(blank=True, help_text='Number of citations (if tracked)', null=True)),
                ('impact_factor', models.DecimalField(blank=True, decimal_places=3, help_text='Journal impact factor', max_digits=6, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False, help_text='Verified by coordinator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publication_date', '-reported_at'],
            },
        ),
    ]
