# Generated by Django 5.0.6 on 2026-01-12 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0002_initial'),
        ('applications', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessgrant',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='core.equipment'),
        ),
        migrations.AddField(
            model_name='historicalaccessgrant',
            name='application',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='applications.application'),
        ),
        migrations.AddField(
            model_name='historicalaccessgrant',
            name='equipment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.equipment'),
        ),
        migrations.AddField(
            model_name='historicalaccessgrant',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpublication',
            name='application',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Application that resulted in this publication', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='applications.application'),
        ),
        migrations.AddField(
            model_name='historicalpublication',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpublication',
            name='reported_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='application',
            field=models.ForeignKey(blank=True, help_text='Application that resulted in this publication', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='applications.application'),
        ),
        migrations.AddField(
            model_name='publication',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='accessgrant',
            unique_together={('application', 'equipment')},
        ),
    ]
