# Generated by Django 5.0.14 on 2025-12-31 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_initial'),
        ('applications', '0006_phase7_acceptance_handoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpublication',
            name='access_grant',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='access_grant',
        ),
        migrations.AddField(
            model_name='historicalpublication',
            name='application',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Application that resulted in this publication', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='applications.application'),
        ),
        migrations.AddField(
            model_name='publication',
            name='application',
            field=models.ForeignKey(blank=True, help_text='Application that resulted in this publication', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='applications.application'),
        ),
    ]
